[2024-09-18T02:31:00.585+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-18T02:31:00.604+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table scheduled__2024-09-04T00:00:00+00:00 [queued]>
[2024-09-18T02:31:00.612+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table scheduled__2024-09-04T00:00:00+00:00 [queued]>
[2024-09-18T02:31:00.613+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 6
[2024-09-18T02:31:00.628+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresOperator): delete_data_from_table> on 2024-09-04 00:00:00+00:00
[2024-09-18T02:31:00.638+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1733) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-18T02:31:00.637+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'delete_data_from_table', 'scheduled__2024-09-04T00:00:00+00:00', '--job-id', '22095', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmppu5my1n8']
[2024-09-18T02:31:00.639+0000] {standard_task_runner.py:72} INFO - Started process 1735 to run task
[2024-09-18T02:31:00.640+0000] {standard_task_runner.py:105} INFO - Job 22095: Subtask delete_data_from_table
[2024-09-18T02:31:00.685+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table scheduled__2024-09-04T00:00:00+00:00 [running]> on host 5508ea9ebfaf
[2024-09-18T02:31:00.766+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v03' AIRFLOW_CTX_TASK_ID='delete_data_from_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-04T00:00:00+00:00'
[2024-09-18T02:31:00.767+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-18T02:31:00.781+0000] {sql.py:266} INFO - Executing: 
                delete from dag_runs where dt = ('2024-09-04' and dag_id = 'dag_with_postgres_operator_v03')
            
[2024-09-18T02:31:00.789+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-18T02:31:00.797+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-18T02:31:00.806+0000] {sql.py:509} INFO - Running statement: 
                delete from dag_runs where dt = ('2024-09-04' and dag_id = 'dag_with_postgres_operator_v03')
            , parameters: None
[2024-09-18T02:31:00.809+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type boolean: "2024-09-04"
LINE 2:                 delete from dag_runs where dt = ('2024-09-04...
                                                         ^

[2024-09-18T02:31:00.820+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v03, task_id=delete_data_from_table, run_id=scheduled__2024-09-04T00:00:00+00:00, execution_date=20240904T000000, start_date=20240918T023100, end_date=20240918T023100
[2024-09-18T02:31:00.839+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-18T02:31:00.840+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 22095 for task delete_data_from_table (invalid input syntax for type boolean: "2024-09-04"
LINE 2:                 delete from dag_runs where dt = ('2024-09-04...
                                                         ^
; 1735)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type boolean: "2024-09-04"
LINE 2:                 delete from dag_runs where dt = ('2024-09-04...
                                                         ^

[2024-09-18T02:31:00.894+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-18T02:31:00.903+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-09-18T02:36:50.514+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-18T02:36:50.535+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table scheduled__2024-09-04T00:00:00+00:00 [queued]>
[2024-09-18T02:36:50.545+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table scheduled__2024-09-04T00:00:00+00:00 [queued]>
[2024-09-18T02:36:50.546+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 6
[2024-09-18T02:36:50.644+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresOperator): delete_data_from_table> on 2024-09-04 00:00:00+00:00
[2024-09-18T02:36:50.653+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2314) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-18T02:36:50.654+0000] {standard_task_runner.py:72} INFO - Started process 2322 to run task
[2024-09-18T02:36:50.653+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'delete_data_from_table', 'scheduled__2024-09-04T00:00:00+00:00', '--job-id', '22149', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmp4a34aply']
[2024-09-18T02:36:50.655+0000] {standard_task_runner.py:105} INFO - Job 22149: Subtask delete_data_from_table
[2024-09-18T02:36:50.711+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table scheduled__2024-09-04T00:00:00+00:00 [running]> on host 5508ea9ebfaf
[2024-09-18T02:36:50.812+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v03' AIRFLOW_CTX_TASK_ID='delete_data_from_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-04T00:00:00+00:00'
[2024-09-18T02:36:50.814+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-18T02:36:50.828+0000] {sql.py:266} INFO - Executing: 
                delete from dag_runs where dt = '2024-09-04' and dag_id = 'dag_with_postgres_operator_v03'
            
[2024-09-18T02:36:50.834+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-18T02:36:50.840+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-18T02:36:50.850+0000] {sql.py:509} INFO - Running statement: 
                delete from dag_runs where dt = '2024-09-04' and dag_id = 'dag_with_postgres_operator_v03'
            , parameters: None
[2024-09-18T02:36:50.853+0000] {sql.py:518} INFO - Rows affected: 0
[2024-09-18T02:36:50.863+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-18T02:36:50.864+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v03, task_id=delete_data_from_table, run_id=scheduled__2024-09-04T00:00:00+00:00, execution_date=20240904T000000, start_date=20240918T023650, end_date=20240918T023650
[2024-09-18T02:36:50.909+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-18T02:36:50.918+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1378 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-09-18T02:36:50.928+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-18T02:36:50.931+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
