[2024-09-10T07:29:53.787+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-10T07:29:53.862+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_V3.second_task scheduled__2022-11-22T00:00:00+00:00 [queued]>
[2024-09-10T07:29:53.880+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_V3.second_task scheduled__2022-11-22T00:00:00+00:00 [queued]>
[2024-09-10T07:29:53.882+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-10T07:29:53.936+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): second_task> on 2022-11-22 00:00:00+00:00
[2024-09-10T07:29:53.957+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_V3', 'second_task', 'scheduled__2022-11-22T00:00:00+00:00', '--job-id', '3898', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmppby0eg4z']
[2024-09-10T07:29:53.962+0000] {standard_task_runner.py:105} INFO - Job 3898: Subtask second_task
[2024-09-10T07:29:53.960+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=17480) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-10T07:29:53.967+0000] {standard_task_runner.py:72} INFO - Started process 17494 to run task
[2024-09-10T07:29:54.172+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_V3.second_task scheduled__2022-11-22T00:00:00+00:00 [running]> on host 5508ea9ebfaf
[2024-09-10T07:29:54.423+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='our_first_dag_V3' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2022-11-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-11-22T00:00:00+00:00'
[2024-09-10T07:29:54.427+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-10T07:29:54.464+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-10T07:29:54.483+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, this is the second task!']
[2024-09-10T07:29:54.500+0000] {subprocess.py:86} INFO - Output:
[2024-09-10T07:29:54.503+0000] {subprocess.py:93} INFO - hey, this is the second task!
[2024-09-10T07:29:54.504+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-10T07:29:54.552+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-10T07:29:54.553+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_V3, task_id=second_task, run_id=scheduled__2022-11-22T00:00:00+00:00, execution_date=20221122T000000, start_date=20240910T072953, end_date=20240910T072954
[2024-09-10T07:29:54.604+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-10T07:29:54.677+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-10T07:29:54.681+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
