[2024-09-18T00:30:04.256+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-18T00:30:04.514+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_taskflow_api_v04.get_name scheduled__2024-09-14T00:00:00+00:00 [queued]>
[2024-09-18T00:30:04.612+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_taskflow_api_v04.get_name scheduled__2024-09-14T00:00:00+00:00 [queued]>
[2024-09-18T00:30:04.685+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-18T00:30:05.114+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): get_name> on 2024-09-14 00:00:00+00:00
[2024-09-18T00:30:05.195+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=197) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-18T00:30:05.197+0000] {standard_task_runner.py:72} INFO - Started process 233 to run task
[2024-09-18T00:30:05.187+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_taskflow_api_v04', 'get_name', 'scheduled__2024-09-14T00:00:00+00:00', '--job-id', '21940', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_taskflow_api.py', '--cfg-path', '/tmp/tmpc0z4q1mw']
[2024-09-18T00:30:05.203+0000] {standard_task_runner.py:105} INFO - Job 21940: Subtask get_name
[2024-09-18T00:30:05.833+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_taskflow_api_v04.get_name scheduled__2024-09-14T00:00:00+00:00 [running]> on host 5508ea9ebfaf
[2024-09-18T00:30:07.544+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_taskflow_api_v04' AIRFLOW_CTX_TASK_ID='get_name' AIRFLOW_CTX_EXECUTION_DATE='2024-09-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-14T00:00:00+00:00'
[2024-09-18T00:30:07.579+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-18T00:30:07.594+0000] {python.py:240} INFO - Done. Returned value was: {'first_name': 'Jerry', 'last_name': 'fauzi'}
[2024-09-18T00:30:07.796+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-18T00:30:07.811+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_taskflow_api_v04, task_id=get_name, run_id=scheduled__2024-09-14T00:00:00+00:00, execution_date=20240914T000000, start_date=20240918T003004, end_date=20240918T003007
[2024-09-18T00:30:08.262+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-18T00:30:08.719+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-18T00:30:08.788+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-09-18T00:30:10.229+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
